### ISSUE TITLE
aiplayerbot feature request/bug

### ISSUE THREAD

**Issue by filipdadgar** [RagedUnicorn/docker-wow-vanilla#1]
First of all, thank you! Love this!

**Request:**
Would it be feasible to add aiplayerbot.conf to _install_dir_/etc/ so I can bring in Bots?

I assume the server build with bot flag is default(make), because this is shown in the log when the server is being brought up: [PlayerBotMgr] Between 0 and 1 bots online.

**Issue:**
The bot commands work but the bots keep "disconnecting".

.bot add charname
brings the bot online, it is also showed in the console that bot logged in, but just a few seconds later it announces the bot has logged out.

**Solution?**
My guess is that there is no botconfig for the server since it is missing in the /etc dir.

**Attempts so far**: Tried to fork the repo and rebuild the image with a small modification to copy an existing aiplayerbot.conf file to /etc. But cannot complete the image build because of tons of grr! mysql-dev dependencies.

Regards,
Filip

**Comment by RagedUnicorn** [comment]
Hi Filip,

Not something that I have planned or tried out. I actually don't think that I will develop this any further because it got quite useless with the release of classic and the big changes to the api.

You can however of course fork the repository and add this config yourself.

For the issues you see you will need to bring the dependencies to an updated version.

ca-certificates="${CA_CERTIFICATES_VERSION}" \
    wget="${WGET_VERSION}" \
    gpg="${GPG_VERSION}" \
    gpg-agent="${GPG_AGENT_VERSION}" \
    gpgconf="${GPG_CONF_VERSION}" \
    dirmngr="${DIRMNGR_VERSION}" \
    nano="${NANO_VERSION}" && \

Versions can be found here: https://packages.ubuntu.com/

Or you can remove the version (not recommended for rebuildable containers but fine for testing) with will then take the newest version.

Cheers,
RagedUnicorn
